-- DEPRECATED: This file is no longer used for database initialization
-- Database schema is now managed via Alembic migrations in /alembic/versions/
-- 
-- To initialize the database, use:
--   alembic upgrade head
--
-- To create new migrations, use:
--   alembic revision --autogenerate -m "Description of changes"
--
-- Migration files are located in: /alembic/versions/
-- - 001_initial_database_schema.py - Base tables
-- - 002_add_cat_recognition_tables.py - Cat recognition features
-- - 003_add_enhanced_activity_features.py - Enhanced activity detection
--
-- For more information, see the migration documentation in the API README.